# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d2612f20e225a0b1b3c32acc7ef91aa4472c1b074795834bed66d310ef5b3884e8126147c84d5cdd31084fc9a35abbb76ae8cc54074bc17358743f4553f5bdbe

test:
  secret_key_base: 717fbb01298d7d7fc2ab2aa39734c788b6509b299ea519c5501b213b7e4ed8823b47f8a839b87dc488562b692bf9a93d857fe2ac947ea0702ff4fa713558bfc8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
